siteWithParseEmails/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('emailapp.urls', namespace='email')),
    path('', include('users.urls', namespace='users')),
    path('auth/', include('social_django.urls', namespace='social'))
]

if settings.DEBUG:
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls")),
                    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

from . import views

app_name = 'user'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.logout, name='logout'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    image = models.ImageField(upload_to='users_images', blank=True, null=True, verbose_name='Аватар')

    class Meta:
        db_table = 'user'
        verbose_name = 'Пользователя'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return self.username

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django.core.exceptions import ValidationError
from users.models import User


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(
        label='username',
        widget=forms.TextInput(
            attrs={"autofocus": True, 'class': 'form-control', 'placeholder': 'Input your username'}
        )
    )

    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={"class": "form-control", "placeholder": "Input your password"}
        )
    )

    class Meta:
        model = User
        fields = ['username', 'password']

    # username = forms.CharField(
    #     label = 'Имя',
    #     widget=forms.TextInput(attrs={"autofocus": True,
    #                                   'class': 'form-control',
    #                                   'placeholder': 'Введите ваше имя пользователя'})
    # )
    # password = forms.CharField(
    #     label = 'Пароль',
    #     widget=forms.PasswordInput(attrs={"autocomplete": "current-password",
    #                                       'class': 'form-control',
    #                                       'placeholder': 'Введите ваш пароль'})
    # )


class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            "username",
            "email",
            "password1",
            "password2",
        )

    username = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "placeholder": "Input your username",
            }
        )
    )

    email = forms.EmailField(
        required=False,
        widget=forms.EmailInput(
            attrs={
                "class": "form-control",
                "placeholder": "Input your email *youremail@example.com",
                # 'readonly': True,
            }
        ),
    )

    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={"class": "form-control", "placeholder": "Input your password"}
        )
    )

    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={"class": "form-control", "placeholder": "Input your password"}
        )
    )


class ProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ("image", "first_name", "last_name", "username", "email")

    first_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "placeholder": "Введите ваше имя",
            }
        )
    )

    last_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "placeholder": "Введите вашу фамилию",
            }
        )
    )

    image = forms.ImageField(
        widget=forms.FileInput(attrs={"class": "img-fluid rounded-circle"}),
        required=False
    )

    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "placeholder": "Введите ваше имя пользователя",
            }
        )
    )

    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                "class": "form-control",
                "placeholder": "Введите ваш email (youremail@example.com)",
            }
        )
    )

users/views.py
from django.contrib.auth.decorators import login_required
from django.contrib import auth, messages
from django.db.models import Prefetch
from django.http import HttpResponseRedirect, HttpResponseBadRequest
from django.shortcuts import redirect, render
from django.urls import reverse
from users.models import User
from .forms import ProfileForm, UserLoginForm, UserRegistrationForm


def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)

            session_key = request.session.session_key

            if user:
                auth.login(request, user)
                messages.success(request, f"{username}, Вы вошли в аккаунт")

                redirect_page = request.POST.get('next', None)
                if redirect_page and redirect_page != reverse('user:logout'):
                    return HttpResponseRedirect(request.POST.get('next'))

                return HttpResponseRedirect(reverse('emailapp:home'))
    else:
        form = UserLoginForm()

    context = {
        'title': 'Home - Authorize',
        'form': form
    }
    return render(request, 'users/login.html', context)


def registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()

            session_key = request.session.session_key

            user = form.instance
            backend = 'django.contrib.auth.backends.ModelBackend'
            auth.login(request, user, backend=backend)

            messages.success(request, f"{user.username}, Вы успешно зарегистрированы и вошли в аккаунт")
            return HttpResponseRedirect(reverse('emailapp:home'))
    else:
        form = UserRegistrationForm()

    context = {
        'title': 'Home - Registration',
        'form': form
    }
    return render(request, 'users/registration.html', context)


@login_required
def profile(request):
    if request.method == 'POST':
        form = ProfileForm(data=request.POST, instance=request.user, files=request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "Profile was updated")
            return HttpResponseRedirect(reverse('user:profile'))
    else:
        form = ProfileForm(instance=request.user)

    context = {
        'title': 'Home - Profile',
        'form': form,
    }
    return render(request, 'users/profile.html', context)


@login_required
def logout(request):
    messages.success(request, f"{request.user.username}, Вы вышли из аккаунта")
    auth.logout(request)
    return redirect(reverse('emailapp:home'))

users/templates/users/login.html
{% extends "base.html" %}
{% load static %}
{% block head %}
<head>
    <link rel="stylesheet" href="{% static 'main/css/login.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Kanit:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
</head>
{% endblock %}
{% block content %}
    <main>
        <div class="block-authorize">
            <h1 class="text-authorize">Authorization</h1>
                <form  action="{% url "users:login" %}" method="post">
                    {% csrf_token %}
                    {% if request.GET.next %}
                    <input type="hidden" name="next" value={{request.GET.next}}>
                    {% endif %}
                        <div class="username-menu">
                            <label for="id_username" class="form-label">Username</label>
                            <input type="text" class="form-control" name="username" id="id_username" placeholder="Input your username" required>
                        </div>
                        <div class="password-menu">
                            <label for="id_password" class="form-label">Password</label>
                            <input type="password" class="form-control" name="password" id="id_password"
                                placeholder="Input you password" required>
                        </div>
                        <button type="submit" class="button-enter" style="cursor: pointer;"><b>Enter</b></button>
                    </form>
            <div class="forget-password-menu">
                <a href="#">Forgot Password?</a> | <a href="{% url "users:registration" %}">Create Account</a>
            </div>
            <hr>
            <div class="buttons-auhorize">
                <p>Or login in via:</p>
                <a href="{% url 'social:begin' 'google-oauth2' %}" class="button-link-log">
                    <img class="mx-1" src="{% static 'main/svg/google.svg' %}" alt="Catalog Icon" width="16" height="16">
                    <b>Google</b>
                </a>
                <a href="{% url 'social:begin' 'facebook' %}" class="button-link-log">
                    <img class="mx-1" src="{% static 'main/svg/facebook.svg' %}" alt="Catalog Icon" width="16" height="16">
                    <b>Facebook</b>
                </a>
                <a href="{% url 'social:begin' 'github' %}" class="button-link-log">
                    <img class="mx-1" src="{% static 'main/svg/github.svg' %}" alt="Catalog Icon" width="16" height="16">
                    <b>GitHub</b>
                </a>
            </div>
        </div>
    </main>
{% endblock %}

users/templates/users/profile.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'main/css/profile.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Kanit:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
{% endblock %}

{% block content %}
    <main>
        <div class="block-profile">
             {% if user.is_authenticated %}
            <h3 class="text-profile-title"style="margin-left: 2%;">User Profile: {{user.username}}
                <div class="line-profile" style="margin-left: -4.5%;"></div>
            </h3>
                <form action="{% url 'user:profile' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="class-row-container">
                        <div class="avatar-input">
                            {% if user.image %}
                                <img src="{{ user.image.url }}"
                                alt="Аватар пользователя" class="img-fluid rounded-circle"
                                style="max-width: 150px;">
                            {% else %}
                                <img src="{% static 'main/images/baseavatar.jpg' %}"
                                    alt="Аватар пользователя" class="img-fluid rounded-circle"
                                    style="max-width: 150px;">
                            {% endif %}
                                <label class="input-file">
                                    <span class="input-file-text">No file selected</span>
                                    <input type="file" name="image" class="input-file-input" id="id_image" accept="image/*">
                                    {% if form.image.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{form.image.errors}}</div>
                                    {% endif %}
                                    <span class="input-file-btn">Choose file</span>
                                </label>
                        </div>

                        <div class="name-input">
                            <label for="id_first_name" class="form-label">Name</label>
                            <input type="text" class="form-control" name="first_name"  id="id_first_name"
                                placeholder="Input your name" value="{{ form.first_name.value }}" required>
                        </div>
                        <div class="lastname-input">
                            <label for="id_last_name" class="form-label">Surname</label>
                            <input type="text" class="form-control" name="last_name" id="id_last_name"
                                placeholder="Input your surname" value="{{ form.last_name.value }}" required>
                        </div>
                        <div class="username-input">
                            <label for="id_username" class="form-label">Username</label>
                            <input type="text" class="form-control" name="username" id="id_username"
                                placeholder="Input your username" value="{{ form.username.value }}" required>
                            {% if form.username.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{ form.username.errors }}</div>
                            {% endif %}
                        </div>
                        <div class="email-input">
                            <label for="id_email" class="form-label">Email</label>
                            <input type="email" class="form-control" name="email" id="id_email"
                                placeholder="Input your email" value="{{ form.email.value }}" required>
                            {% if form.email.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{ form.email.errors }}</div>
                            {% endif %}
                        </div>
                    </div>
                    <button type="submit" class="button-link-log">Save</button>
                    <button type="submit" class="button-link-log"><a href="{% if user.is_authenticated %}{% url 'users:logout' %}{% endif %}" style="text-decoration: none; color: #fff;">Exit</a></button>
                </form>
            {% endif %}
        </div>
    </main>
    <script src="{% static 'main/js/file-avatar.js' %}"></script>
{% endblock %}

users/templates/users/registration.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'main/css/login.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Kanit:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
{% endblock %}

{% block content %}
    <main>
        <div class="block-authorize">
            <h1 class="text-authorize">Registration</h1>
                <form action="{% url 'user:registration' %}" method="post">
                    {% csrf_token %}
                    <div class="username-menu">
                        <label for="id_username" class="form-label" style="margin-top: 10%;">Username</label>
                        <input type="text" class="form-control" value="{% if form.username.value %}{{ form.username.value }}{% endif %}"
                               id="id_username" name="username" placeholder="Input username" required>
                        {% if form.username.errors %}
                            <div class="alert alert-danger alert-dismissible fade show">{{ form.username.errors }}</div>
                        {% endif %}
                    </div>

                    <div class="password-menu">
                        <label for="id_password1" class="form-label">Password</label>
                        <input type="password" class="form-control" value="{% if form.password1.value %}{{ form.password1.value }}{% endif %}"
                               id="id_password1" name="password1" placeholder="Input password" required>
                        {% if form.password1.errors %}
                            <div class="alert alert-danger alert-dismissible fade show">{{ form.password1.errors }}</div>
                        {% endif %}
                    </div>

                    <div class="confirmpassword-menu">
                        <label for="id_password2" class="form-label" style="margin-top: 1%; margin-left: 7%;">Confirm Password</label>
                        <input type="password" class="form-control" value="{% if form.password2.value %}{{ form.password2.value }}{% endif %}"
                               id="id_password2" name="password2" placeholder="Confirm Password" required style="margin-left: 4%;">
                        {% if form.password2.errors %}
                            <div class="alert alert-danger alert-dismissible fade show">{{ form.password2.errors }}</div>
                        {% endif %}
                    </div>

                    <div class="email-menu" style="margin-left: 3%;">
                        <label for="id_email" class="form-label" style="margin-left: 3%; margin-top: 1%;">Email</label>
                        <input type="email" class="form-control" value="{% if form.email.value %}{{ form.email.value }}{% endif %}"
                               id="id_email" name="email" placeholder="Input your email *youremail@example.com" required>
                        {% if form.email.errors %}
                            <div class="alert alert-danger alert-dismissible fade show">{{ form.email.errors }}</div>
                        {% endif %}
                    </div>

                    <button type="submit" class="button-enter" style="cursor: pointer;"><b>Enter</b></button>
                </form>
            <div class="forget-password-menu">
                <a href="{% url 'user:login' %}">Have account?</a> | <a href="login.html">Enter in Account</a>
            </div>
        </div>
    </main>
{% endblock %}